Imports System
Imports System.IO
Imports System.Text
Imports CASTCommon.ModPublic

Public Class KFJP059
    Inherits CAstReports.ClsReportBase

    Sub New()
        ' CSVファイルセット
        InfoReport.ReportName = "KFJP059"
    End Sub

    Public Overrides Function CreateCsvFile() As String

        Dim file As String = MyBase.CreateCsvFile

        'タイトル行
        CSVObject.Output("システム日付")
        CSVObject.Output("タイムスタンプ")
        CSVObject.Output("ログイン名")
        CSVObject.Output("端末名")
        CSVObject.Output("取引先主コード")
        CSVObject.Output("取引先副コード")
        CSVObject.Output("媒体コード")
        CSVObject.Output("ラベル区分")
        CSVObject.Output("コード区分")
        CSVObject.Output("代表委託者コード")
        CSVObject.Output("ファイル名")
        CSVObject.Output("フォーマット区分")
        CSVObject.Output("マルチ区分")
        CSVObject.Output("入出金区分")
        CSVObject.Output("種別")
        CSVObject.Output("委託者コード")
        CSVObject.Output("委託者名カナ")
        CSVObject.Output("取扱金融機関コード")
        CSVObject.Output("取扱金融機関名")
        CSVObject.Output("取扱支店コード")
        CSVObject.Output("取扱支店名")
        CSVObject.Output("科目")
        CSVObject.Output("口座番号")
        CSVObject.Output("持込区分")
        CSVObject.Output("送信区分")
        CSVObject.Output("他行区分")
        CSVObject.Output("自振契約作成区分")
        CSVObject.Output("摘要区分")
        CSVObject.Output("カナ摘要")
        CSVObject.Output("漢字摘要")
        CSVObject.Output("振替コード")
        CSVObject.Output("企業コード")
        CSVObject.Output("委託社名漢字")
        CSVObject.Output("郵便番号")
        CSVObject.Output("電話番号")
        CSVObject.Output("FAX番号")
        CSVObject.Output("顧客番号")
        CSVObject.Output("関連企業情報")
        CSVObject.Output("委託者住所漢字")
        CSVObject.Output("郵送先名カナ")
        CSVObject.Output("郵送先名漢字")
        CSVObject.Output("１日")
        CSVObject.Output("２日")
        CSVObject.Output("３日")
        CSVObject.Output("４日")
        CSVObject.Output("５日")
        CSVObject.Output("６日")
        CSVObject.Output("７日")
        CSVObject.Output("８日")
        CSVObject.Output("９日")
        CSVObject.Output("１０日")
        CSVObject.Output("１１日")
        CSVObject.Output("１２日")
        CSVObject.Output("１３日")
        CSVObject.Output("１４日")
        CSVObject.Output("１５日")
        CSVObject.Output("１６日")
        CSVObject.Output("１７日")
        CSVObject.Output("１８日")
        CSVObject.Output("１９日")
        CSVObject.Output("２０日")
        CSVObject.Output("２１日")
        CSVObject.Output("２２日")
        CSVObject.Output("２３日")
        CSVObject.Output("２４日")
        CSVObject.Output("２５日")
        CSVObject.Output("２６日")
        CSVObject.Output("２７日")
        CSVObject.Output("２８日")
        CSVObject.Output("２９日")
        CSVObject.Output("３０日")
        CSVObject.Output("３１日")
        CSVObject.Output("振替休日シフト")
        CSVObject.Output("１月")
        CSVObject.Output("２月")
        CSVObject.Output("３月")
        CSVObject.Output("４月")
        CSVObject.Output("５月")
        CSVObject.Output("６月")
        CSVObject.Output("７月")
        CSVObject.Output("８月")
        CSVObject.Output("９月")
        CSVObject.Output("１０月")
        CSVObject.Output("１１月")
        CSVObject.Output("１２月")
        CSVObject.Output("再振契約")
        CSVObject.Output("再振副コード")
        CSVObject.Output("日数／基準日(再振)")
        CSVObject.Output("日付区分(再振)")
        CSVObject.Output("再振休日シフト")
        CSVObject.Output("契約日")
        CSVObject.Output("開始年月")
        CSVObject.Output("終了年月")
        CSVObject.Output("持込期日")
        CSVObject.Output("日数／基準日(依頼書)")
        CSVObject.Output("日付区分(依頼書)")
        CSVObject.Output("依頼書休日シフト")
        CSVObject.Output("依頼書種別")
        CSVObject.Output("依頼書出力順")
        CSVObject.Output("定額区分")
        CSVObject.Output("受付明細表出力区分")
        CSVObject.Output("不能結果明細表出力区分")
        CSVObject.Output("印刷部数")
        CSVObject.Output("結果返却要否")
        CSVObject.Output("結果明細データ作成区分")
        CSVObject.Output("振替結果変換テーブルID")
        CSVObject.Output("決済区分")
        CSVObject.Output("とりまとめ店コード")
        CSVObject.Output("とりまとめ店名")
        CSVObject.Output("本部別段口座番号")
        CSVObject.Output("日数／基準日(決済)")
        CSVObject.Output("日付区分(決済)")
        CSVObject.Output("決済休日シフト")
        CSVObject.Output("決済金融機関コード")
        CSVObject.Output("決済金融機関名")
        CSVObject.Output("決済支店コード")
        CSVObject.Output("決済支店名")
        CSVObject.Output("決済科目")
        CSVObject.Output("決済口座番号")
        CSVObject.Output("決済名義人(カナ)")
        CSVObject.Output("備考１")
        CSVObject.Output("備考２")
        CSVObject.Output("手数料徴求支店コード")
        CSVObject.Output("手数料徴求支店名")
        CSVObject.Output("手数料徴求科目")
        CSVObject.Output("手数料徴求口座番号")
        CSVObject.Output("手数料徴求区分")
        CSVObject.Output("手数料徴求方法")
        CSVObject.Output("手数料集計周期")
        CSVObject.Output("日数／基準日(手数料徴求)")
        CSVObject.Output("日付区分(手数料徴求)")
        CSVObject.Output("手数料徴求休日シフト")
        CSVObject.Output("手数料請求区分")
        CSVObject.Output("振替手数料単価")
        CSVObject.Output("消費税区分")
        CSVObject.Output("送料")
        CSVObject.Output("固定手数料１")
        CSVObject.Output("固定手数料２")
        CSVObject.Output("集計基準月")
        CSVObject.Output("集計終了日")
        CSVObject.Output("集計基準")
        CSVObject.Output("集計方法")
        CSVObject.Output("集計企業ＧＲＰ")
        CSVObject.Output("振込手数料基準ＩＤ")
        CSVObject.Output("自店１万円未満")
        CSVObject.Output("自店１万円以上３万円未満")
        CSVObject.Output("自店３万円以上")
        CSVObject.Output("本支店１万円未満")
        CSVObject.Output("本支店１万円以上３万円未満")
        CSVObject.Output("本支店３万円以上")
        CSVObject.Output("他行１万円未満")
        CSVObject.Output("他行１万円以上３万円未満")
        CSVObject.Output("他行３万円以上")
        CSVObject.Output("暗号化処理区分")
        CSVObject.Output("ＡＥＳオプション")
        CSVObject.Output("暗号化キー１")
        CSVObject.Output("暗号化キー２")
        CSVObject.Output("印紙税１")
        CSVObject.Output("印紙税２")
        CSVObject.Output("印紙税３")
        CSVObject.Output("相手センター確認ＣＤ")
        CSVObject.Output("当方センター確認ＣＤ")
        CSVObject.Output("伝送ファイルＩＤ")
        CSVObject.Output("搬送方法")
        CSVObject.Output("搬送ルート１")
        CSVObject.Output("搬送ルート２")
        CSVObject.Output("搬送ルート３")
        CSVObject.Output("返却支店コード")
        CSVObject.Output("返却支店")
        CSVObject.Output("照合要否区分")
        CSVObject.Output("契約書番号")
        CSVObject.Output("個別前処理")
        CSVObject.Output("個別後処理")
        CSVObject.Output("特記事項")
        CSVObject.Output("受付特記事項")
        CSVObject.Output("返却特記事項")
        CSVObject.Output("搬送特記事項")
        CSVObject.Output("", False, True)

        Return file
    End Function

    '
    ' 機能　 ： 取引先マスタメンテ(登録)をデータに書き込む
    '
    ' 備考　 ： 
    '
    Public Sub OutputCsvData(ByVal data As String, Optional ByVal dq As Boolean = False, Optional ByVal crlf As Boolean = False)
        CSVObject.Output(data, dq, crlf)
    End Sub

    Protected Overrides Sub Finalize()
        MyBase.Finalize()
    End Sub
End Class
